### ISSUE TITLE
O Jupyter Notebook não tá rodando no meu PC

### ISSUE THREAD

**Issue by andregrijo62** [mat-esp/python-intro-2#1]
Professor, 

instalei o Anaconda, o Jupyter, mas quando fui rodar, apareceu isso. 
C:\Users\André\Anaconda3>jupyter notebook Esta versão de C:\Users\André\Anaconda3\Scripts\jupyter.exe não é compatível com a versão do Windows sendo executada. Verifique as informações de sistema do computador e contate o fornecedor do software. Abaixo segue as configurações do meu pc. Não tô achando nada na internet de como "consertar" isso. 
![issue matesp](https://cloud.githubusercontent.com/assets/14278441/10394494/07cccaac-6e6e-11e5-8b41-890106d14780.png)

**Comment by leouieda** [comment]
@andregrijo62 pois é, isso tem acontecido com pessoas que tem Win 32bits instalado em processador de 64bit (que é o seu caso).

Uma gambiarra para funcionar é a seguinte:

1. Na pasta `C:\Users\André\Anaconda3\Scripts` ache o arquivo `jupyter_notebook_script.py` (ou algo semelhante)
2. Copie esse arquivo para sua pasta (por exemplo, `C:\Users\André`)
3. Para rodar o notebook, vá (no bash) até a pasta onde você copiou o `.py' e rode `python jupyter_notebook_script.py`

Isso deveria funcionar. A coisa chata é que você precisa estar na pasta onde está o `.py` para rodar o jupyter. Mas funciona.

**Comment by andregrijo62** [comment]
Professor, 
Deu certo aqui já. Brigadão
Att, 
André Mejia GrijóEstudante de Oceanografia- Uerj

Date: Fri, 9 Oct 2015 11:19:11 -0700
